### ISSUE TITLE
Feature request ~ port status?

### ISSUE THREAD

**Issue by Trigger-broom-289** [antiguru/ykush2#2]
Hi Moritz,

Is there a way to query the actual status of each port?
I would like to have something like the following if possible please
ykush2 -h all -s
with -s = status returning either on or off
with all = all boards

Regards
Stephane

**Comment by antiguru** [comment]
Hi Stephane,
that sounds like a useful tool. At the moment it is not possible to query the hub for its state, so the ykush2 tool would need to save that on the computer it is running on. I might have a look when I have some spare time.
Best,
Moritz

**Comment by Trigger-broom-289** [comment]
Thanks Moritz.

**Comment by Trigger-broom-289** [comment]
forgot to close this one. all good now.
